#!/data/data/com.termux/files/usr/bin/bash
Help()
{
              echo "𝐓𝐡𝐢𝐬 𝐭𝐨𝐨𝐥 𝐦𝐚𝐤𝐢𝐧𝐠 𝐩𝐮𝐛𝐠 90𝐟𝐩𝐬 version(1.2)" >&2
              echo
              echo "𝐒𝐲𝐧𝐭𝐞𝐱: 𝐓𝐞𝐦𝐩𝐥𝐚𝐭𝐞𝐬 [-g|h|x|v]"
              echo "Options:"
              echo "-𝐠 , --𝐠𝐟𝐱 ,𝐠𝐟𝐱             𝐟𝐨𝐫 𝐠𝐟𝐱 𝐭𝐨𝐨𝐥"
              echo "-𝐡 , --𝐡𝐞𝐥𝐩 , 𝐡𝐞𝐥𝐩     𝐟𝐨𝐫 𝐡𝐞𝐥𝐩"
              echo "-𝐱 , --𝐠𝐢𝐭 , 𝐠𝐢𝐭              𝐟𝐨𝐫 𝐠𝐢𝐭𝐡𝐮𝐛"
              echo "-𝐯 , --𝐯𝐞𝐫𝐬𝐢𝐨𝐧 , 𝐯𝐞𝐫𝐬𝐢𝐨𝐧 𝐟𝐨𝐫 𝐯𝐞𝐫𝐬𝐢𝐨𝐧"
              echo
}
Help
gfx()
{
spinner() {
echo '
               ┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
               │  │ │├─┤ │││││││ ┬
               ┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
progreSh() {
    LR='\033[1;31m'
    LG='\033[1;32m'
    LY='\033[1;33m'
    LC='\033[1;36m'
    LW='\033[1;37m'
    NC='\033[0m'
    if [ "${1}" = "0" ]; then TME=$(date +"%s"); fi
    SEC=`printf "%04d\n" $(($(date +"%s")-${TME}))`; SEC="$SEC sec"
    PRC=`printf "%.0f" ${1}`
    SHW=`printf "%3d\n" ${PRC}`
    LNE=`printf "%.0f" $((${PRC}/2))`
    LRR=`printf "%.0f" $((${PRC}/2-12))`; if [ ${LRR} -le 0 ]; then LRR=0; fi;
    LYY=`printf "%.0f" $((${PRC}/2-24))`; if [ ${LYY} -le 0 ]; then LYY=0; fi;
    LCC=`printf "%.0f" $((${PRC}/2-36))`; if [ ${LCC} -le 0 ]; then LCC=0; fi;
    LGG=`printf "%.0f" $((${PRC}/2-48))`; if [ ${LGG} -le 0 ]; then LGG=0; fi;
    LRR_=""
    LYY_=""
    LCC_=""
    LGG_=""
    for ((i=1;i<=13;i++))
    do
    	DOTS=""; for ((ii=${i};ii<13;ii++)); do DOTS="${DOTS}."; done
    	if [ ${i} -le ${LNE} ]; then LRR_="${LRR_}█"; else LRR_="${LRR_}."; fi
    	echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${DOTS}${LY}............${LC}............${LG}............ ${SHW}%${NC}\r"
    	if [ ${LNE} -ge 1 ]; then sleep .025; fi
    done
    for ((i=14;i<=25;i++))
    do
    	DOTS=""; for ((ii=${i};ii<25;ii++)); do DOTS="${DOTS}."; done
    	if [ ${i} -le ${LNE} ]; then LYY_="${LYY_}█"; else LYY_="${LYY_}."; fi
    	echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${DOTS}${LC}............${LG}............ ${SHW}%${NC}\r"
    	if [ ${LNE} -ge 14 ]; then sleep .030; fi
    done
    for ((i=26;i<=37;i++))
    do
    	DOTS=""; for ((ii=${i};ii<37;ii++)); do DOTS="${DOTS}."; done
    	if [ ${i} -le ${LNE} ]; then LCC_="${LCC_}█"; else LCC_="${LCC_}."; fi
    	echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${LC}${LCC_}${DOTS}${LG}............ ${SHW}%${NC}\r"
    	if [ ${LNE} -ge 26 ]; then sleep .025; fi
    done
    for ((i=38;i<=49;i++))
    do
    	DOTS=""; for ((ii=${i};ii<49;ii++)); do DOTS="${DOTS}."; done
    	if [ ${i} -le ${LNE} ]; then LGG_="${LGG_}█"; else LGG_="${LGG_}."; fi
    	echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${LC}${LCC_}${LG}${LGG_}${DOTS} ${SHW}%${NC}\r"
    	if [ ${LNE} -ge 38 ]; then sleep .025; fi
    done
}

printf "\n\n\n\n\n\n\n\n\n\n"
progreSh 0
progreSh 10
progreSh 20
progreSh 30
progreSh 40
progreSh 50
progreSh 70
progreSh 100
printf "\n\n\n\n\n\n\n\n\n\n"

sleep 1
clear
}
clear
OPC=$(dialog --menu "do you want to continue" 45 60 20 \
1 "yes" \
2 "No" --stdout )

echo $OPC
case $OPC in
1) clear
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo""
echo  '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo""
echo""
echo""
echo""
echo "               "/█1%...................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo  '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/█4%....................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/█8%......................./
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/██10%....................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/██12%....................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/███15%..................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "               "/█████19%..................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "               "/██████28%..................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/████████30%................../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/██████████40%................/
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/█████████████50%............./
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/████████████████60%........../
sleep 0.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo '
┬  ┌─┐┌─┐┌┬┐┬┌┐┌┌─┐
│  │ │├─┤ │││││││ ┬
┴─┘└─┘┴ ┴─┴┘┴┘└┘└─┘
'
echo " "
echo " "
echo " "
echo " "
echo "                "/███████████████████88%......./
sleep 2.0
clear
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
termux-dialog -t "𝙳𝚘 𝚈𝚘𝚞 𝚆𝚊𝚗𝚝 𝚃𝚘 𝙲𝚘𝚗𝚝𝚒𝚗𝚞𝚎
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && exit
termux-setup-storage
clear
echo -e "\e[42mcoping Temp Files To Temp Data\e[m"
sleep 3
while :
do
echo -e "\e[31m[\e[33m01\e[31m]\e[32m 𝐁𝐚𝐭𝐭𝐞𝐥 𝐠𝐫𝐨𝐮𝐧𝐝 𝐌𝐨𝐛𝐢𝐥𝐞 𝐈𝐧𝐝𝐢𝐚1.4 \e[m "
echo -e "\e[31m[\e[33m02\e[31m]\e[32m 𝐏𝐮𝐛𝐠 𝐌𝐨𝐛𝐢𝐥𝐞 𝐆𝐥𝐨𝐛𝐚𝐥 1.4 \e[m "
echo -e "\e[31m[\e[33m03\e[31m]\e[32m 𝐏𝐮𝐛𝐠 𝐌𝐨𝐛𝐢𝐥𝐞 𝐊𝐫 1.4 \e[m "
echo -e "\e[31m[\e[33m04\e[31m]\e[32m 𝐏𝐮𝐛𝐠 𝐌𝐨𝐛𝐢𝐥𝐞 𝐯𝐧 1.4  \e[m "
echo -e "\e[31m[\e[33m05\e[31m]\e[32m 𝐆𝐚𝐦𝐞 𝐅𝐨𝐫 𝐏𝐞𝐚𝐜𝐞  1.13.𝐱 \e[m "
echo -e "\e[31m[\e[33m06\e[31m]\e[32m 𝙴𝚡𝚒𝚝 \e[m "
read -p $'\e[32m>> 𝑺𝒆𝒍𝒆𝒄𝒕 𝒀𝒐𝒖𝒓 𝑶𝒑𝒕𝒊𝒐𝒏:\e[m ' n
tput civis
if [ $n = 1 ] || [ $n = 01 ]
then
cp -r /data/data/com.termux/files/usr/bin/⠀/game_patch_1.4.0.14924.pak /sdcard/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
echo -e "\e[42mcoping \e[m"
sleep 3
echo -e "\e[41mcomplete Now Enjoy The Game With 90 fps\e[m"
termux-dialog -t "𝘿𝙤 𝙮𝙤𝙪 𝙬𝙖𝙣𝙩 𝙩𝙤 𝙤𝙥𝙚𝙣 𝙜𝙖𝙢𝙚 𝙙𝙞𝙧𝙚𝙘𝙩𝙡𝙮
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && exit
clear
spinner

echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
am start --user 0 -n com.pubg.imobile/com.epicgames.ue4.SplashActivity
clear
elif [ $n = 2 ] || [ $n = 02 ]
then
cp -r /data/data/com.termux/files/usr/bin/⠀/game_patch_1.4.0.14924.pak /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
echo -e "\e[42mcoping \e[m"
sleep 3
echo -e "\e[41mcomplete Now Enjoy The Game With 90 fps\e[m"
termux-dialog -t "𝘿𝙤 𝙮𝙤𝙪 𝙬𝙖𝙣𝙩 𝙩𝙤 𝙤𝙥𝙚𝙣 𝙜𝙖𝙢𝙚 𝙙𝙞𝙧𝙚𝙘𝙩𝙡𝙮
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && exit
clear
spinner

echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
am start --user 0 -n com.tencent.ig/com.epicgames.ue4.SplashActivity
clear
elif [ $n = 3 ] || [ $n = 03 ]
then
cp -r /data/data/com.termux/files/usr/bin/⠀/game_patch_1.4.0.14924.pak /sdcard/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
echo -e "\e[42mcoping \e[m"
sleep 3
echo -e "\e[41mcomplete Now Enjoy The Game With 90 fps\e[m"
termux-dialog -t "𝘿𝙤 𝙮𝙤𝙪 𝙬𝙖𝙣𝙩 𝙩𝙤 𝙤𝙥𝙚𝙣 𝙜𝙖𝙢𝙚 𝙙𝙞𝙧𝙚𝙘𝙩𝙡𝙮
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && exit
clear 
spinner
echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
am start --user 0 -n com.pubg.krmobile/com.epicgames.ue4.SplashActivity
clear
elif [ $n = 4 ] || [ $n = 04 ]
then
cp -r /data/data/com.termux/files/usr/bin/⠀/game_patch_1.4.0.14924.pak /sdcard/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks
echo -e "\e[42mcoping \e[m"
sleep 3
echo -e "\e[41mcomplete Now Enjoy The Game With 90 fps\e[m"
termux-dialog -t "𝘿𝙤 𝙮𝙤𝙪 𝙬𝙖𝙣𝙩 𝙩𝙤 𝙤𝙥𝙚𝙣 𝙜𝙖𝙢𝙚 𝙙𝙞𝙧𝙚𝙘𝙩𝙡𝙮
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && tput reset && exit
clear
spinner
echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
am start --user 0 -n com.vng.pubgmobile/com.epicgames.ue4.SplashActivity
clear
elif [ $n = 5 ] || [ $n = 05 ]
then
cp -r /data/data/com.termux/files/usr/bin/⠀/UserCustom.ini /sdcard/Android/data/com.tencent.tmgp.pubgmhd/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/
echo -e "\e[42mcoping \e[m"
sleep 3
echo -e "\e[41mcomplete Now Enjoy The Game With 90 fps\e[m"
termux-dialog -t "𝘿𝙤 𝙮𝙤𝙪 𝙬𝙖𝙣𝙩 𝙩𝙤 𝙤𝙥𝙚𝙣 𝙜𝙖𝙢𝙚 𝙙𝙞𝙧𝙚𝙘𝙩𝙡𝙮
Ans in yes or no" | grep -q "yes"; [ $? -ne 0 ] && exit
clear
spinner
echo '
_                    _
| |                  | |
| |__   ___  __ _ ___| |_
|  _ \ / _ \/ _` / __| __|
| |_) |  __/ (_| \__ \ |_
|_.__/ \___|\__,_|___/\__|'|lolcat
echo ""
echo ""
echo "               "[██████████████████████ 100%]
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 1.0
am start --user 0 -n com.tencent.tmgp.pubgmhd/com.epicgames.ue4.SplashActivity
clear
elif [ $n = 6 ] || [ $n = 06 ]
then
clear
tput reset
exit
else
echo -e  "\e[33m[\e[31m!\e[33m]\e[31m Invalid option try again \e[m"
sleep 2
clear
fi
done;;
2) echo -e  "\e[31m[\e[32m=\e[31m]\e[34m Thanks For Install My Tool \e[m" 
sleep 3
exit;;
*) echo -e  "\e[33m[\e[31m!\e[33m]\e[31m Invalid option try again \e[m"
clear 
sleep 3
exit;;
esac
}
git()
{
clear
printf "\n\n\n\n\n\n"
echo opening
xdg-open https://github.com/hk4crprasad
printf "\n\n\n\n\n\n"
}
version()
{
printf "\n\n\n\n\n\n"
clear
echo -e "  𝕍𝕖𝕣𝕤𝕚𝕠𝕟 \e[31m1.2\e[m"
printf "\n\n\n\n\n\n"
}
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help|help) echo; shift ;;
        -g|gfx|--gfx) gfx; shift ;;
        -x|--git|git) clear; git; shift ;;
        -v|--version|version) clear; version; shift ;;
        # ... (same format for other required arguments)
        *) echo "𝑼𝒏𝒌𝒏𝒐𝒘𝒏 𝒖𝒔𝒂𝒈𝒆 : $1" ;;
    esac
    shift
done
