#!/data/data/com.termux/files/usr/bin/bash
apt update -y ; apt upgrade -y ; apt install git -y
apt install ncurses-utils -y
chmod 700 gfx
cp -r ⠀ gfx /data/data/com.termux/files/usr/bin
spinlong ()
{
echo -e "\n"
bar=" installing........................................ "
printf "\n"
barlength=${#bar}
i=0
while ((i < 100)); do
n=$((i*barlength / 100))
printf "\e[00;32m\r%-${barlength}s\e[00m" "${bar:0:n}"
((i += RANDOM%5+2))
sleep 0.09
done
}
spinlong
echo -e "\e[31m[\e[33m-\e[31m]\e[32m Type gfx at anywhere to install 90fps \e[m "
chmod 700 /data/data/com.termux/files/usr/bin/gfx
